### PR TITLE
Fix #444

### LINKED ISSUE #444: Ruleset updates on every run
### What happened?

Pulumi wants to update `cloudflare.Ruleset` on every execution, even though it shows no changes.
This behaviour started after we upgraded to v5, on v4 it worked correctly.

### Expected Behavior

Update `cloudflare.Ruleset` only if the definition of the resource was changed.

### Steps to reproduce

Add new `cloudflare.Ruleset` to the source code and run `pulumi up` to create the resource. Then run `pulumi up` and pulumi will try to update the resource.

### Output of `pulumi about`

CLI          
Version      3.75.0
Go Version   go1.20.6
Go Compiler  gc

Host     
OS       darwin
Version  13.2.1
Arch     arm64

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
Fix #444  - using a pre-release bridge version with a surgical fix for the root-cause of #444

### CODE REVIEW

**Comment by VenelinMartinov** [comment]
Do you need to randomise the name so it doesn't clash with other test runs?

I restarted it but this is the error:
```
      	* error creating zone "ts-test-cloudflare-zone.com": ts-test-cloudflare-zone.com already exists (1061)
```

**Review by VenelinMartinov — APPROVED** [review]

File: examples/examples_nodejs_test.go [hunk 1]
```diff
@@ -20,6 +20,15 @@ func TestAccRecordTs(t *testing.T) {
 	integration.ProgramTest(t, &test)
 }
 
+func TestRegress444(t *testing.T) {
```
Comment (VenelinMartinov) [inline examples/examples_nodejs_test.go:23]: Shouldn't the test run `pulumi up` twice to reproduce the issue?
